name: 'IndexNow'
on:
  schedule:
    # Set the schedule time
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      lastmod_required:
        description: 'Require a <lastmod> value for submitted URLs'
        required: false
        default: false
        type: boolean

jobs:
  check-and-submit:
    runs-on: ubuntu-latest
    steps:
      - name: indexnow-action
        uses: bojieyang/indexnow-action@v3
        with:
          sitemap-location: 'https://kw.media/sitemap-index.xml'
          key: ${{ secrets.INDEXNOW_KEY }}
          limit: 10000
          lastmod-required: ${{ github.event_name == 'workflow_dispatch' && inputs.lastmod_required == false && 'false' || 'true' }}
